### ISSUE TITLE
What about ES6 or Typescript? 

### ISSUE THREAD

**Issue by ZAYEC77** [jiisoft/jii#1]
There are some JS "versions" with well implementation of classes. Maybe you can use one of they.

**Comment by affka** [comment]
Я так понимаю, можно и по-русски ответить=)

Я думал об использовании es6/coffe/typescript, но пока не решаюсь это использовать по следующим причинам:
1. Многие разработчики не знают формата es6/coffe/typescript и это будет дополнительный порог
2. Могут быть проблемы с библиотеками, которые не адаптированы к этому формату, и речь даже не о typescript, с ним вообще геморой.
3. Нужен препроцессинг для node.js, на сколько я помню. А я хочу чтоб любая библиотека могла работать с Jii, без конфликтов.

В общем, это все круто и заманчиво, но пока что нет. Возможно в будущем, когда для es6 не нужно будет компиляции в es5 для старых браузеров.

**Comment by ZAYEC77** [comment]
@affka, посмотрите на [Babel](https://babeljs.io/) с ним все довольно просто.
Пока объемы кода не очень сильно выросли, может стоит сделать такую миграцию.

**Comment by affka** [comment]
Сколько кода - не особо важно. Его сейчас уже очень много, но в любом случае поменять классы - подъемная задача.
Balel (раньше назывался es6to5) я смотрел ранее. Аргументы все те же.

**Comment by Arilas** [comment]
Обратите внимание на React, где сделана возомжность как использовать нативные классы, так и React.createClass. Никакого увеличения сложности от этого не будет, даже наоборот, с учетом того, что вы делаете клон Yii, пользователям намного проще работать именно с классами (со статическими свойствами, методами, и т.д.) чем с этой странной конструкцией, которая вообще не похожа ни на один фреймворк в js.

**Comment by affka** [comment]
Спасибо, посмотрю. Видимо и правда переделаю все на es6, раз много людей его просят.

**Comment by affka** [comment]
Посмотрел React, посмотрел es6. Минусы вот какие:
1. Для node.js нужен препроцессинг (io.js поддерживает)
2. В es6 нет неймспейсов из коробки. А это значит что класс по прежнему просто функция, у которой максимум есть только свое имя. Мне же часто нужно полное имя класса (с неймспейсом) для отображения исключений, указания и поиск класса по его названию.. 
Вообще я конечно понимаю почему их нет, common js же все таки, но как реализовать все прелести Yii без этого - есть идеи, но нужно эксперементировать.

**Comment by asdf404** [comment]
@affka 
1. компилировать ES6 → ES5 можно при паблише в npm с помощью [prepublish](https://docs.npmjs.com/misc/scripts) скрипта; а запускать без компиляции с помощью [babel-node](https://babeljs.io/docs/usage/cli/).
2. почему нельзя сделать для неймспейсов что-то вроде `import ActiveRecord from 'jii/active-record'`? И зачем выводить полное имя класса с "неймспейсом", если можно вывести стек-трейс, из которого понятно что и где сломалось?

**Comment by affka** [comment]
1. Как компилировать - понятно, запускать через babel-node - дополнительно всем разработчикам его поставить еще нужно..
2. Имя класса может много где указывать как текст (в конфигурации, например) - как указывать такое имя? module:jii-ar-sq/ActiveRecord? А потом еще метод отдельный создавать для его загрузки

**Comment by asdf404** [comment]
1. не нужно его ставить всем. Я же написал про prepublish. Когда вы делаете `npm publish`, то перед тем, как залить пакет в npm, оно компиляется в ES5 и пушится уже скомпиленная версия (если она не проигнорирована в `.npmignore` или `.gitignore` если первого нет).

**Comment by affka** [comment]
В таких исходниках сложнее будет ковыряться, чтоб найти какой-нить баг (если вы не разработчик Jii, а просто установили его через npm install).
Мне часто приходится копаться в исходниках библиотек/фреймворков, чтобы понять как оно работает, зачастую потому что документация еще слабая.

**Comment by jestonedev** [comment]
соглашусь с affka, периодически ковыряюсь в исходнике Yii просто потому что с учетом подробных комментариев так получается быстрее найти необходимый функционал, а также понять как работает что-то слабо документированное. Прекомпиляция убьет такую возможность. Ну либо альтернативный вариант - писать в ES6, но публиковать в npm два варианта: чистый ES6 без препроцессинга и precompiled ES5 with minifications, чтобы разработчики сами могли выбрать.

**Comment by affka** [comment]
Тикет закрываю. Обсуждение и реализацию классов по ES6 откладываю на 2016-й год, когда node.js и io.js будут помержены и в ноде появятся классы без всяких harmony

**Comment by affka** [comment]
node.js и io.js уже объединились! Хотя обещали только в 16ом году.
Теперь нода поддерживает ES6 - https://new.nodejs.org/en/blog/release/v4.0.0/
Это убирает главный стоппер на перенос Jii на ES6.

**Comment by affka** [comment]
Задачка для тех, кто хотел es6 - https://toster.ru/q/276621

**Comment by LestaD** [comment]
Так-то уже 7 версия ноды с нативными async/await
А здесь всё ещё без классов и явного импорта

**Comment by affka** [comment]
Не все сразу, но классы es6 уже появились, можно посмотреть на любой из файлов - https://github.com/jiisoft/jii/blob/master/base/Application.js
Так что по-маленьку в этом направлении исправляемся :)
