### ISSUE TITLE
Будет ли поддержка ES6-7?

### ISSUE THREAD

**Issue by LestaD** [jiisoft/jii#16]
Есть несколько предложений по улучшению фреймворка для совместимости с ES6:

импорты: лучше расположить base.controller и base.model не в общем пакете, а например во вложенности.
классы: посмотрите как реализует классы сейчас [babel](http://babeljs.io/repl)

как я бы хотел:

``` javascript

import { Controller } from 'jii/base';

export default class SiteController extends Controller {
  actionIndex() {
    this.render('index', { text: 'Hello World!' });
    // Фреймворк должен сам отправлять данные клиенту
  }
}
```

[LestaD/Jii-Boilerplate-Basic-NextGenJS](https://github.com/LestaD/jii-boilerplate-basic)
Сейчас лучше развивать фреймворк в сторону js, так как node.js имеет отличную архитектуру от php, соответственно фреймворк должен иметь свою структуру

**Comment by LestaD** [comment]
Также очень хотелось бы иметь поддержку любого шаблонизатора, например Jade
По мне он лучше:

```jade
html
  head
    title=title
  body
    h1=title
    p=content
```

**Comment by LestaD** [comment]
Я перепишу boilerplate, ради примера того, как это могло бы быть реализовано в стиле es6
Результат положу сюда

**Comment by affka** [comment]
По ES6 было много рассуждений, я пришел к тому, что пока node.js не будет нативно поддерживать es6 формат, перехода на es6 не буду делать.

> По мне он лучше чем ejs:
ejs - это чисто расширение файла, чтоб IDE не тупило и понимало js в html. Шаблонизатор сейчас там undercore, но поставить другой - легко, под это есть абстракция.

> Я перепишу boilerplate, ради примера
Будет интересно посмотреть, спасибо! Ваш пример в первом комментарии выглядит весьма красиво!

> Сейчас лучше развивать фреймворк в сторону js
Из Yii хочется перенимать принципы, подходы. Все не получится, но многое уже миграровало успешно. Тут от языка не все зависит, Yii много чего взял из Ruby, например.
Основная фишка Jii - это знакомость API. Поэтому совпадение хочу делать максимально возможное, на сколько это позволяет различие языков и здравый смысл :)

**Comment by LestaD** [comment]
@affka да перенимать принципы можно, но всё должно быть в рамках идеологии node.js

**Comment by LestaD** [comment]
@affka я готов показать Вам концепт того как может выглядеть Jii в идеале.
[LestaD/Jii-Boilerplate-Basic-NextGenJS](https://github.com/LestaD/jii-boilerplate-basic)
Часть функционала, включая классы уже поддерживается в io.js(node.js) >= 3.0

**Comment by affka** [comment]
Спасибо, выглядит неплохо.
От неймспейсов в таком случае нужно будет вообще отказаться.. хотя вот тут что-то осталось - "className: JiiMysql.Connection,"
там не должно быть типа 
import { Connection as JiiMysqlConnection } from 'jii/sql/mysql';
?

Можно ли без JiiAR, JiiView и прочих переименований сделать? дефисы в названиях пакетов мешают же?

**Comment by LestaD** [comment]
@affka на самом деле можно импорты называть как угодно, тут дело вкуса и линтера.
В данном концепте я представил куда можно двигаться Jii.

**Comment by LestaD** [comment]
@affka хотя если хорошо подумать, то архитектурно, наверно, лучше сделать так:

```javascript
import Jii, { UrlManager, View, AssetManager } from 'jii';
import { Mysql as JiiMysql } from 'jii/sql';
import { ActiveRecord } from 'jii/base';
import HttpServer from 'jii/server';
```

То есть поместить общие компоненты в `jii`, http-сервер выделить в отдельный файл `jii/server`, в 'jii/base' положить общие компоненты, от которых следует наследоваться, а в 'jii/sql' положить всё что связано с SQL, просто экспортировать под разными именами.
В случае поддержки NoSQL сделать точно такой же API как у `jii/sql`, но для `jii/nosql`. Туда например Mongo, TingoDB.

**Comment by LestaD** [comment]
@affka кстати декораторы из ES7 можно использовать как трейты php

**Comment by affka** [comment]
> http-сервер выделить в отдельный файл jii/server

файл? или папку?
Я не особо знаю синтаксис ES6, поэтому хочу уточнить:

> import Jii, { UrlManager, View, AssetManager } from 'jii';

это означает, что в пакете лежат файлы index.js (Jii), UserManager.js, View.js, AssetManager.js?

> import { ActiveRecord } from 'jii/base';

А это - что в пакете есть папка base и в ней файл ActiveRecord.js?

Я так понимаю, что это преобразуется в
var ActiveRecord = require('jii/base/ActiveRecord') ?

**Comment by affka** [comment]
и еще вопрос - как дела обстоят у IDE, в частности IDEA (WebStorm/PhpStorm) - подсказывает ли он классы, добавляет ли он их автоматом в секцию import, как это он делает с секцией use в php?

**Comment by affka** [comment]
Ух ты, node.js и io.js уже объединились! Хотя обещали только в 16ом году.
Теперь нода поддерживает ES6 - https://new.nodejs.org/en/blog/release/v4.0.0/
Это убирает главный стоппер на перенос Jii на ES6.

**Comment by ZAYEC77** [comment]
@affka касательно именно продуктов Jetbrains, они имеют поддержку TypeScript и ES6 классы.
Еще знаю, что Visual Studio точно потдерживает TS)

**Comment by LestaD** [comment]
@affka Введение в CommonJS Modules:

```js
import name from 'package';
```
означает 

```js
var name = require('package');
```

Далее вложенные части

```js
import name from 'package/add';
```

означает

```js
var name = require('package/add')
// внутри пакета под именем package есть файл add.js
```


далее деструктуризация:

```js
import { foo, bar } from 'package';
```

это значит что мы импортируем `foo` и `bar` из пакета `package`;
чтобы их импортировать из пакета, надо чтобы пакет их экспортировал

```js
// package

export function foo() {
   // any code
}

export const bar = 'special constant or variable';
```

реально выглядит как-то так:

```js
module.exports.foo = function() {
  // any code
}

module.exports.bar = 'special constant or variable';
```

!но!

мы не можем получить сразу всё с помощью конструкции импорта по умолчанию:

```js
import all from 'package';

all === {}; // true
```

для такого нужно экспортировать по умолчанию нужный объект:

```js
export default class World {}

export function bar() {}

export const foo = 'const';
```

импорт всего этого добра будет выглядеть так:

```js
import World, { bar, foo } from 'package';
```


А теперь что такое деструктуризация на очень явных примерах:

```js
let Obj = {
  name : 'lestad',
  age: 20
}

let { Name, Age } = Obj;
```

babel трансформирует в старый js:

```js
var Obj = {
  name: 'lestad',
  age: 20
};

var Name = Obj.Name;
var Age = Obj.Age;
```

Не сильно сложно

**Comment by LestaD** [comment]
Да и кстати, лучше не делать никаких `globals`!

**Comment by affka** [comment]
Спасибо за примеры! Globals и пишу только в примерах, чтобы было проще въехать разработчику. Сам Jii не регистрирует глобальных переменных.

**Comment by LestaD** [comment]
@affka обновил примеры)

**Comment by LestaD** [comment]
вот ещё небольшой пример импортов из реального проекта:

```js
import React, { Component } from 'react';
import Modal from 'react-modal';
import Svgo from 'Element/Svgo/ElementSvgo';

import { close, afterClose, PopupList, show } from 'actions/ModalActions';
import { logout } from 'actions/AccountActions';

import WidgetLogin from 'Widget/Login/WidgetLogin';
import ModalCloseButton from 'Widget/Modal/CloseButton';
import WidgetRegistration from 'Widget/Registration/WidgetRegistration';
import WidgetMobileApprove from 'Widget/MobileApprove/WidgetMobileApprove';
```

**Comment by LestaD** [comment]
лучше по возможность отказывать от нескольких фреймворков, вроде lodash и underscore одновременно. Я вот, для объединения объектов использую такую функцию:

```js
/**
 * Deep merge objects
 * @param {...Object} objects Any listed object
 */
export function MergeObjects(...objects) {
  let result = {};
  for (let current of objects) {
    for (let key in current) {
      if (current.hasOwnProperty(key)) {
        if (typeof current[key] === "object" && typeof result[key] === "object") {
          result[key] = MergeObjects(result[key], current[key]);
        }
        else {
          result[key] = current[key];
        }
      }
    }
  }
  return result;
}
```



Парочка примеров использования декораторов: [lestad/es6-decorators](https://github.com/LestaD/ES6-Decorators)

**Comment by affka** [comment]
я не вижу применения для экспорта набора методов/свойств, у меня в каждом файле по классу всегда. А значит будет всегда типа:
import WidgetLogin from 'Widget/Login/WidgetLogin';

где Widget/Login по сути является неймспейсом, а WidgetLogin - названием класса.

**Comment by affka** [comment]
В Jii сейчас только функционал underscore используется. Для мержа объектов (а он нужен только для мержа конфигов) - я тоже свой метод написал.

**Comment by LestaD** [comment]
> я не вижу применения для экспорта набора методов/свойств, у меня в каждом файле по классу всегда. А значит будет всегда 
> import WidgetLogin from 'Widget/Login/WidgetLogin';

Так и должно быть, это подход ES6. Вы всегда явно определяете ЧТО хотите иметь в своём файле.
В Java (который является родителем JS) сделано именно так:

```java
import com.java.name;
```

Require all это очень плохая практика. yii2 строится таким образом, что в процессе выполнения подключаются только нужные файлы, а ведь в yii2 файлов тысячи.

**Comment by LestaD** [comment]
Вот пример из реального проекта, в котором очень много файлов.
А это лишь малая часть

![screen shot 2015-09-10 at 13 23 19](https://cloud.githubusercontent.com/assets/5620073/9785977/25a6ee88-57bf-11e5-864c-ab3443c3cee8.png)

**Comment by LestaD** [comment]
@affka попробуйте такой редактор как SublimeText.
Ответственно заявляю как программист, он очень крут, особенно с большим количеством плагинов.

**Comment by affka** [comment]
В моей работе Sublime'a будет мало, я PhpStorm юзаю :) Он не идеал, но лучшей альтернативы не знаю. Sublime отличный редактор, и им тоже пользуюсь иногда. Но это не IDE.

> Require all это очень плохая практика.
Да, это костыль был, даже скорее временный. В пхп подобный подход был бы проблемным, т.к. пхп каждый раз умирает и часть файлов действительно излишне грузилась бы, а нода загружается один раз и время загрузки не сильно критично. Расход памяти от этого тоже не думаю что сильно увеличивался бы.

> Вот пример из реального проекта
а почему *.jsx? Что "х" значит?

**Comment by LestaD** [comment]
@affka `jsx` — формат js включающий поддержку синтаксического сахара для React.js

По поводу `require all`, не во всех проектах нужна вся мощь фреймворка, ОЧЕНЬ хотелось бы, чтобы фреймворк подгружал только то, что нужно

**Comment by LestaD** [comment]
Example of jsx:

```jsx
import React, { Component } from 'react';

export default class User extends Component {
  render() {
    return (
      <div class="User">{this.props.username}</div>
    );
  }
}
```

**Comment by LestaD** [comment]
Возьмем к примеру, у меня есть проект на express, при старте он занимает около 100Мб в ОЗУ.
Если не заходить в админку, и пользоваться только клиент-сайд, то займет памяти не больше 200Мб.
НО если полезть в админку, то всё станет интереснее, занимаемая приложением память увеличится до 500Мб.

Так о чём я, если я запускаю уже настроенный проект, я не хочу чтобы он сам по себе загружал ВСЁ! Хочется чтобы только то, что нужно. иначе ужс был б. Если бы не освобождение памяти по требованию, то приложение уже перевалило бы за 1ГБ ОЗУ, а мне нельзя, на вдс и так не много памяти

**Comment by affka** [comment]
что-то сильно большие расходы памяти у вас для express, но в любом случае согласен, что фреймворк не должен все разом подключать. Учту это, когда буду переписывать под ES6

**Comment by LestaD** [comment]
@affka Просто у меня в приложении ОЧЕНЬ много моделей и мало контроллеров/роутов.
Пользователю дано редактировать почти всё что он видит.

**Comment by affka** [comment]
что-то не видно поддержки импортов в node.js - https://nodejs.org/en/docs/es6/
в io.js этого тоже получается небыло?

**Comment by LestaD** [comment]
@affka импорты будут не скоро. Но если фреймворк не поддерживает качественные импорты в ES6 это существенный минус.
Когда я говорил про es6 я имел ввиду нативное создание классов по месту
когда `class Foo {}` идентично `(function(){ function Foo(){}})()`.
В данный момент в Jii нельзя создать просто класс через `Jii.createClass` он определяется где-то, но не здесь

**Comment by affka** [comment]
Задачка для тех, кто хотел es6 - https://toster.ru/q/276621

**Comment by LestaD** [comment]
@affka ответ: не нужно смешивать разные подходы

**Comment by affka** [comment]
Jii перешел на es6 классы и поддержку es6. Тема более не актуальна
