### ISSUE TITLE
Jii.httpServer.HttpServer

### ISSUE THREAD

**Issue by wirwolf** [jiisoft/jii#18]
Если я хочу добавить в веб сервер express какие то свои use. Я делаю прослойку 
Jii.defineClass('app.Components.HttpServer', {

	__extends: Jii.httpServer.HttpServer,
а в конфиге 
http: {
				className: 'app.Components.HttpServer',
				staticDirs: __dirname + '/../public/img/',
			},
в которой в init this._express.use но это не работает так как в родительском init есть такая строчка
this._express.all('*', this._onRoute.bind(this));
после нее все use игнорируются. Предлагаю переместить ее в start. 
![117](https://cloud.githubusercontent.com/assets/8457572/10186532/67f51d28-675a-11e5-9a57-fee11e06bdcb.png)

**Comment by affka** [comment]
Вообще да, можно, это ничего не сломает точно. Но вообще в будущем я хотел избавиться от express, потому что подобные зависимости могут служить дополнительными утечками процессора/памяти.

**Comment by wirwolf** [comment]
А какой тогда http сервер использовать?

**Comment by affka** [comment]
нативный, на чем express и работает.
