### ISSUE TITLE
Controller Camel Case bug

### ISSUE THREAD

**Issue by wirwolf** [jiisoft/jii#19]
https://github.com/jiisoft/jii/blob/master/lib/base/Controller.js#L178
Регулярка не пропускает Camel Case. actionGetByProjectId не отрабатывает

**Comment by affka** [comment]
Баг не совсем в этом, но баг был.
Action id в вашем случае (в роуте) должен указываться как site/get-by-project-id.

**Comment by wirwolf** [comment]
Зачем в контроллере называть метод по по одному а в браузере путь к нему по другому. Mне и в Yii2 приходилось фиксить это прослойкой контроллера

**Comment by affka** [comment]
Это уже идеология Yii, так стало во второй версии, которой я придерживаюсь. Почему так сделали точно не знаю, но думаю аргументы какие-то были.
Как по мне - регистронезависемые пути с дефисами смотрятся в адресных строках гораздо приятнее.
